name: Deploy to Production
run-name: Deploy to Production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Specify the environment with required approvals
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy to Production
        run: echo "Deploying to production..."
